export const PHRASE_FAMILIES=[
 {familyId:'anchor-do-sol',title:'DO ↔ SOL Anchor',stage:0,structure:'two staff landmarks',line:['C','G'],cells:[['C','G'],['G','C']],harmonyRoles:['tonic','fifth'],variants:['anchor-cg-01','anchor-gc-01','anchor-ccgg-01'],source:{type:'curriculum',hamaseRef:null,sourcePage:null,analysisRef:null}},
 {familyId:'do-sol-in-time',title:'DO / SOL in Time',stage:1,structure:'tonic/fifth phrase under rhythmic change',line:['C','G','C'],cells:[['C','G']],harmonyRoles:['tonic','fifth'],variants:['do-sol-q-01','do-sol-rest-01','do-sol-eighth-01','do-sol-pickup-01'],source:{type:'curriculum',hamaseRef:null,sourcePage:null,analysisRef:null}},
 {familyId:'tonic-shape',title:'Tonic Shape',stage:2,structure:'C-E-G as one shape',line:['C','E','G'],cells:[['C','E'],['E','G']],harmonyRoles:['root','third','fifth'],variants:['tonic-shape-01','tonic-shape-02'],source:{type:'curriculum',hamaseRef:null,sourcePage:null,analysisRef:null}},
 {familyId:'descend-to-mi',title:'G → E',stage:3,structure:'descending motion toward E',line:['G','F','E'],cells:[['G','E'],['G','F'],['F','E']],harmonyRoles:['fifth','third'],variants:['desc-mi-seed','desc-mi-grow'],source:{type:'curriculum',hamaseRef:null,sourcePage:null,analysisRef:null}},
 {familyId:'descend-to-do',title:'E → C',stage:3,structure:'descending motion toward C',line:['E','D','C'],cells:[['E','C'],['E','D'],['D','C']],harmonyRoles:['third','root'],variants:['desc-do-seed','desc-do-grow','desc-do-change'],source:{type:'curriculum',hamaseRef:null,sourcePage:null,analysisRef:null}},
 {familyId:'second-harmonic-family',title:'Shared Shape',stage:4,structure:'the known tonic shape expands into C/C6, then the same tertian visual logic is encountered as Am7 and Dm7',line:['stacked-third-shape'],cells:[],harmonyRoles:['shape-family'],variants:['second-c','second-c6','second-am7','second-dm7'],source:{type:'curriculum',hamaseRef:null,analysisRef:'C / C6 / Am7 / Dm7を共有shape familyとして経験',curriculumRef:'教材の方針 rev.3 Stage 4'}},
 {familyId:'ii-v-i-voice-line',title:'Across the Barline',stage:5,structure:'two-bar ii-V-I phrase whose voice-leading remains continuous across harmony and the barline',line:['F','F','E'],cells:[],harmonyRoles:['ii','V','I'],variants:['ii-v-i-seed','ii-v-i-grow'],source:{type:'curriculum',hamaseRef:null,analysisRef:'voice-leadingを中心にbarlineを跨いだphraseへ進む',curriculumRef:'教材の方針 rev.3 Stage 5'}},
];
export const familyById=id=>PHRASE_FAMILIES.find(f=>f.familyId===id)||null;
export const familiesForStage=stage=>PHRASE_FAMILIES.filter(f=>f.stage===Number(stage));
export const familiesThroughStage=stage=>PHRASE_FAMILIES.filter(f=>f.stage<=Number(stage));
