export const PHRASE_FAMILIES=[
 {familyId:'anchor-do-sol',title:'DO ↔ SOL Anchor',stage:0,structure:'two staff landmarks',line:['C','G'],cells:[['C','G'],['G','C']],harmonyRoles:['tonic','fifth'],variants:['anchor-cg-01','anchor-gc-01','anchor-ccgg-01'],source:{type:'curriculum',hamaseRef:null,sourcePage:null,analysisRef:null}},
 {familyId:'do-sol-in-time',title:'DO / SOL in Time',stage:1,structure:'tonic/fifth phrase under rhythmic change',line:['C','G','C'],cells:[['C','G']],harmonyRoles:['tonic','fifth'],variants:['do-sol-q-01','do-sol-rest-01','do-sol-eighth-01'],source:{type:'curriculum',hamaseRef:null,sourcePage:null,analysisRef:null}},
 {familyId:'tonic-shape',title:'C–E–G Shape',stage:2,structure:'C-E-G as one shape',line:['C','E','G'],cells:[['C','E'],['E','G']],harmonyRoles:['root','third','fifth'],variants:['tonic-shape-01','tonic-shape-02'],source:{type:'curriculum',hamaseRef:null,sourcePage:null,analysisRef:null}},
 {familyId:'descend-to-mi',title:'G → E',stage:3,structure:'descending motion toward E',line:['G','F','E'],cells:[['G','E'],['G','F'],['F','E']],harmonyRoles:['fifth','third'],variants:['desc-mi-seed','desc-mi-grow'],source:{type:'curriculum',hamaseRef:null,sourcePage:null,analysisRef:null}},
 {familyId:'descend-to-do',title:'E → C',stage:3,structure:'descending motion toward C',line:['E','D','C'],cells:[['E','C'],['E','D'],['D','C']],harmonyRoles:['third','root'],variants:['desc-do-seed','desc-do-grow','desc-do-change'],source:{type:'curriculum',hamaseRef:null,sourcePage:null,analysisRef:null}},
 {familyId:'fill-line-desc',title:'Down → Filled Line',stage:4,structure:'descending chord-tone skeleton remains stable while offbeat passing tones fill the surface',line:['b7','5','3','1'],cells:[['b7','5'],['5','3'],['3','1']],harmonyRoles:['root','third','fifth','seventh'],harmonyContext:'C7',variants:['cti-desc-seed','cti-desc-pass'],source:{type:'hamase-rule',hamaseRef:'ex.001',analysisRef:'分散和音→音階化',textPages:[20],scorePages:[21],preparedImages:['pages/page_0021.jpg']}},
 {familyId:'fill-line-asc',title:'Up → Filled Line',stage:4,structure:'ascending chord-tone skeleton remains stable while offbeat passing tones fill the surface',line:['1','3','5','b7'],cells:[['1','3'],['3','5'],['5','b7']],harmonyRoles:['root','third','fifth','seventh'],harmonyContext:'C7',variants:['cti-asc-seed','cti-asc-pass'],source:{type:'hamase-rule',hamaseRef:'ex.005',analysisRef:'上昇音階型分散和音',textPages:[22,23],scorePages:[23],preparedImages:['pages/page_0023.jpg']}},
 {familyId:'grow-g-to-f',title:'G → F / Grow',stage:5,structure:'the G-to-F line remains invariant while upper motion and rhythm create denser surfaces',line:['G','F'],cells:[['G','F']],harmonyRoles:[],harmonyContext:'C',variants:['gf-seed','gf-upper','gf-arch','gf-rhythm'],source:{type:'curriculum-derived',hamaseRef:null,analysisRef:'LINEAR LINEを不変項としてsurfaceを増やす',curriculumRef:'教材の方針 rev.3 §10',crossAnalysisRef:'章横断分析 §3–4'}},
];
export const familyById=id=>PHRASE_FAMILIES.find(f=>f.familyId===id)||null;
export const familiesForStage=stage=>PHRASE_FAMILIES.filter(f=>f.stage===Number(stage));
export const familiesThroughStage=stage=>PHRASE_FAMILIES.filter(f=>f.stage<=Number(stage));
