export const STAGES = [
  { stage: 0, id: 'staff-anchor', title: 'Staff Anchor', unlock: { notes: ['C4','G4'], rhythm: ['quarter'] }, field: 'training-4', gate: 'ドとソを、拍から落ちずに初見で歌える' },
  { stage: 1, id: 'do-sol-in-time', title: 'DO / SOL in Time', unlock: { notes: ['C4','G4'], rhythm: ['quarter','eighth-pair','rest','pickup','offbeat-entry'] }, field: 'training-4', gate: 'ドとソの短い譜面を、休符や8分音符があっても流れの中で歌える' },
  { stage: 2, id: 'tonic-shape', title: 'Tonic Shape', unlock: { notes: ['C4','E4','G4'], rhythm: ['quarter'] }, field: 'training-4', gate: 'C–E–Gを一音ずつではなく、一つのshapeとして読める' },
  { stage: 3, id: 'make-the-line', title: 'Make the Line', unlock: { notes: ['B3','C4','D4','E4','F4','G4'], rhythm: ['quarter','eighth-pair'] }, field: 'training-4', gate: 'Tonic Shapeに音が加わっても、一つの線として読んで歌える' },
  { stage: 4, id: 'second-harmonic-family', title: 'Second Harmonic Family', unlock: { notes: ['A3','C4','D4','E4','F4','G4','A4','C5'], rhythm: ['quarter'], harmony: ['C','C6','Am7','Dm7'] }, field: 'training-4', gate: 'C / C6 / Am7 / Dm7で、似たshapeを五線譜から歌える' },
  { stage: 5, id: 'dominant-ii-v-i', title: 'Dominant / ii–V–I', unlock: { notes: ['C4','D4','E4','F4','G4','A4','B4'], rhythm: ['quarter','two-bar'], harmony: ['Dm7','G7','Cmaj7'] }, field: 'training-4', phraseBeats: 8, gate: '2小節の譜面を、barlineを越えて線を切らずに歌える' },
  { stage: 6, id: 'two-generators', title: 'Two Generators', unlock: { notes: ['B3','C4','D4','E4','F4','G4','A4','B4','C5'], rhythm: ['quarter','two-bar'], harmony: ['Cmaj7','Am7','FMaj7','Dm7','G7','Em7'], generators: ['harmony-to-line','line-to-cell-to-harmony'] }, field: 'training-4', phraseBeats: 8, gate: '同じ下降の動きを、異なる生成系列から育った普通の譜面としてcold readできる' },
  { stage: 7, id: 'cell-grammar', title: 'CELL Grammar', unlock: { notes: ['B3','C4','D4','E4','F4','G4','A4','B4','C5'], rhythm: ['quarter','eighth-pair'], transform: ['same-target-surface-change'] }, field: 'training-4', gate: 'G→Fという同じ到達運動を、表面の音数や形が変わっても普通の譜面からcold readできる' },
  { stage: 8, id: 'ornament-direction', title: 'Ornament as Direction', unlock: { notes: ['B3','C4','D4','E4','F4','F#4','G4','A4','B4'], rhythm: ['quarter','eighth-pair'], transform: ['passing','neighbor','appoggiatura','turn','chromatic-approach'] }, field: 'training-4', gate: '装飾音が増えても、どこへ向かうlineかを失わず普通の譜面からcold readできる' },
  { stage: 9, id: 'chord-change-long-line', title: 'Chord Change / Long Line', unlock: { notes: ['B3','C4','D4','E4','F4','G4','A4','B4','C5'], rhythm: ['half','quarter','two-bar','four-bar'], harmony: ['Cmaj7','Am7','FMaj7','Dm7'], phraseBeats: [8,16], fieldProgression: ['training-4','phrase-8'] }, field: 'phrase-8', phraseBeats: 16, gate: '和声が小節ごとに変わっても、4小節の下降LINEAR LINEを切らずにcold readできる' },
];
export const stageByNumber = stage => STAGES.find(s => s.stage === Number(stage)) || null;
export const stagesThrough = stage => STAGES.filter(s => s.stage <= Number(stage));
