export const STAGES = [
  { stage: 0, id: 'staff-anchor', title: 'Staff Anchor', unlock: { notes: ['C4','G4'], rhythm: ['quarter'] }, field: 'training-4', gate: 'ドとソを、拍から落ちずに初見で歌える' },
  { stage: 1, id: 'do-sol-in-time', title: 'DO / SOL in Time', unlock: { notes: ['C4','G4'], rhythm: ['quarter','eighth-pair','rest','pickup','offbeat-entry'] }, field: 'training-4', gate: 'ドとソの短い譜面を、休符や8分音符があっても流れの中で歌える' },
  { stage: 2, id: 'tonic-shape', title: 'Tonic Shape', unlock: { notes: ['C4','E4','G4'], rhythm: ['quarter'] }, field: 'training-4', gate: 'C–E–Gを一音ずつではなく、一つのshapeとして読める' },
  { stage: 3, id: 'make-the-line', title: 'Make the Line', unlock: { notes: ['B3','C4','D4','E4','F4','G4'], rhythm: ['quarter','eighth-pair'] }, field: 'training-4', gate: 'Tonic Shapeに音が加わっても、一つの線として読んで歌える' },
  { stage: 4, id: 'second-harmonic-family', title: 'Second Harmonic Family', unlock: { notes: ['A3','C4','D4','E4','F4','G4','A4','C5'], rhythm: ['quarter'], harmony: ['C','C6','Am7','Dm7'] }, field: 'training-4', gate: 'C / C6 / Am7 / Dm7で、似たshapeを五線譜から歌える' },
  { stage: 5, id: 'dominant-ii-v-i', title: 'Dominant / ii–V–I', unlock: { notes: ['C4','D4','E4','F4','G4','A4','B4'], rhythm: ['quarter','two-bar'], harmony: ['Dm7','G7','Cmaj7'] }, field: 'training-4', phraseBeats: 8, gate: '2小節の譜面を、barlineを越えて線を切らずに歌える' },
  { stage: 6, id: 'two-generators', title: 'Two Generators', unlock: { notes: ['B3','C4','D4','E4','F4','G4','A4','B4','C5'], rhythm: ['quarter','two-bar'], harmony: ['Cmaj7','Am7','FMaj7','Dm7','G7','Em7'], generators: ['harmony-to-line','line-to-cell-to-harmony'] }, field: 'training-4', phraseBeats: 8, gate: '同じ下降の動きを、異なる生成系列から育った普通の譜面としてcold readできる' },
  { stage: 7, id: 'cell-grammar', title: 'CELL Grammar', unlock: { notes: ['B3','C4','D4','E4','F4','G4','A4','B4','C5'], rhythm: ['quarter','eighth-pair'], transform: ['same-target-surface-change'] }, field: 'training-4', gate: 'G→Fという同じ到達運動を、表面の音数や形が変わっても普通の譜面からcold readできる' },
  { stage: 8, id: 'ornament-direction', title: 'Ornament as Direction', unlock: { notes: ['B3','C4','D4','E4','F4','F#4','G4','A4','B4'], rhythm: ['quarter','eighth-pair'], transform: ['passing','neighbor','appoggiatura','turn','chromatic-approach'] }, field: 'training-4', gate: '装飾音が増えても、どこへ向かうlineかを失わず普通の譜面からcold readできる' },
  { stage: 9, id: 'chord-change-long-line', title: 'Chord Change / Long Line', unlock: { notes: ['B3','C4','D4','E4','F4','G4','A4','B4','C5'], rhythm: ['half','quarter','two-bar','four-bar'], harmony: ['Cmaj7','Am7','FMaj7','Dm7'], phraseBeats: [8,16], fieldProgression: ['training-4','phrase-8'] }, field: 'phrase-8', phraseBeats: 16, gate: '和声が小節ごとに変わっても、4小節の下降LINEAR LINEを切らずにcold readできる' },
  { stage: 10, id: 'relative-major', title: 'Relative Major', unlock: { notes: ['B3','C4','D4','E4','F4','G4','A4','B4','C5','E5'], rhythm: ['quarter'], harmony: ['F','G7'], transform: ['harmonic-reinterpretation','extend-to-maj7','flat-fifth-one-note-change'] }, field: 'phrase-8', gate: '同じF–A–C shapeを背景FとG7の両方で読み、F–A–C–EからCだけBへ動く一音CHANGEもcold readできる' },
  { stage: 11, id: 'relative-minor', title: 'Relative Minor', unlock: { notes: ['Ab3','B3','C4','D4','E4','F4','Ab4','A4','B4','C5','D5'], rhythm: ['quarter','eighth-pair'], harmony: ['F','Fm','G7'], transform: ['major-to-minor-one-note-change','reuse-flat-fifth','keep-line-through-mode-change'] }, field: 'phrase-8', gate: '既知Major shapeを一声だけ変えてMinor shapeへ移し、下降lineもMajor→Minorの境界で止めずcold readできる' },
  { stage: 12, id: 'tonic-minor-tonal-field', title: 'Tonic Minor / Tonal Field', unlock: { notes: ['G3','A3','Ab3','B3','C4','D4','Eb4','F4','G4','A4','B4'], rhythm: ['quarter','eighth-pair','two-bar','four-bar'], harmony: ['Cm','Dm7b5','G7'], tonalFields: ['c-minor-melodic','c-minor-harmonic'], transform: ['skeleton-to-filled-line','multi-bar-tonal-field'] }, field: 'phrase-8', phraseBeats: [8,16], gate: 'scale名を頼らず、骨格から育ったminor lineと、和声が変わっても続く数小節のC minor tonal fieldをcold readできる' },
  { stage: 13, id: 'density-double-time', title: 'Density / Double Time', unlock: { notes: ['F4','F#4','G4','A4','Bb4','B4','D5'], rhythm: ['quarter','eighth-pair','16th'], harmony: ['G7'], transform: ['arpeggiate','scalarize','chromaticize','rhythmic-compression'], difficultyAxis: 'density', bpmPolicy: 'hold' }, field: 'phrase-8', phraseBeats: 4, gate: 'BPMを上げず、既知G→F cellが2音から16音へ高密度化しても同じ動きとしてcold readできる' },
  { stage: 14, id: 'forms-flow', title: 'Blues / Rhythm Changes', unlock: { forms: ['c-blues-12','rhythm-changes-32'], transform: ['harmonic-move','form-position-move','connect','trade','flow'], integrationFamilyIds: ['g-to-f-surfaces','density-g-to-f','relative-major-reinterpret','relative-minor-line'] }, field: 'c-blues-12', fieldProgression: ['c-blues-12','rhythm-changes-32'], gate: '12-bar Blues / 32-bar Rhythm Changesの時間から落ちず、既知の動きを別の和声位置・form位置でも読み、つなげられる' },
];
export const stageByNumber = stage => STAGES.find(s => s.stage === Number(stage)) || null;
export const stagesThrough = stage => STAGES.filter(s => s.stage <= Number(stage));
