const N=(pitch,midi,startBeat,duration)=>({pitch,midi,startBeat,duration,rest:false});
const R=(startBeat,duration)=>({pitch:null,midi:null,startBeat,duration,rest:true});
const V=(variantId,familyId,phase,notes,{parentVariant=null,morphType='NONE',morphTargets=[],allowedPresentation=['COLD_READ'],coldReadEligible=true,allowedHarmony=['C'],source=null,ornamentType=null,targetRole=null}={})=>({variantId,familyId,phase,parentVariant,notes,rhythm:'4/4',meter:[4,4],morphType,morphTargets,allowedKeys:['C'],allowedHarmony,allowedPresentation,coldReadEligible,source,ornamentType,targetRole});
const TEACH=['TEACHER_CALL','BUILD','COLD_READ','DELAYED_READ'];
const LEARN=['BUILD','COLD_READ','DELAYED_READ'];
const STAGE4_SOURCE={type:'curriculum',hamaseRef:null,analysisRef:'C / C6 / Am7 / Dm7を共有shape familyとして経験',curriculumRef:'教材の方針 rev.3 Stage 4'};
const STAGE5_SOURCE={type:'curriculum',hamaseRef:null,analysisRef:'voice-leadingを中心にbarlineを跨いだphraseへ進む',curriculumRef:'教材の方針 rev.3 Stage 5'};
const STAGE6_HARMONY_SOURCE={type:'hamase',hamaseRef:'ex.085',sourcePage:58,analysisRef:'ex.085 — 6度コード・チェンジの理論モデル',adaptation:'C Major pedagogical reduction; source is a theory diagram, not copied surface notation'};
const STAGE6_LINE_SOURCE={type:'hamase',hamaseRef:'ex.269',sourcePage:234,sourceWork:'Ballade',analysisRef:'ex.269 — リニア・ラインとその構成セルによる和声の細分化',adaptation:'C-major pedagogical reduction of the line-first generator; not the original Ballade surface'};
const STAGE7_SOURCE={type:'hamase',hamaseRef:'ex.087',sourcePage:59,sourcePages:[59,60],sourceWork:"Billie’s Bounce [take 1]",analysisRef:'ex.087 — CELLの分節と可変なsurface',adaptation:'C-major pedagogical reduction of the invariant/surface principle; source analytic chord labels are not used as sounding accompaniment'};
const STAGE8_PASSING_SOURCE={type:'hamase',hamaseRef:'ex.001',sourcePage:21,sourceWork:'Red Cross [take 1]',analysisRef:'chordal skeletonの間へpassing toneを入れてscalar surfaceへ育てる',adaptation:'G→E C-major pedagogical reduction of the verified passing-tone operator'};
const STAGE8_NEIGHBOR_SOURCE={type:'hamase',hamaseRef:'ex.008',sourcePage:24,sourceWork:'I Got Rhythm',analysisRef:'親音→上方刺繍→親音→下降targetというneighbor motion',adaptation:'G→E C-major pedagogical reduction of the verified upper-neighbor operator'};
const STAGE8_APPOGGIATURA_SOURCE={type:'hamase',hamaseRef:'ex.162',sourcePage:131,sourceWork:'Night and Day',analysisRef:'C triad skeletonにEへの前打音Fを加えlineを作る',adaptation:'G→E fragment reduced from the verified C-major target-directed appoggiatura principle'};
const STAGE8_CHROMATIC_SOURCE={type:'hamase',hamaseRef:'ex.019',sourcePage:28,sourceWork:'Thriving from a Riff [take 3]',analysisRef:'和声音へ短2度下から前打音を当てる',adaptation:'F#→G lower-semitone approach inserted inside the known G→E movement'};
const STAGE8_TURN_SOURCE={type:'hamase',hamaseRef:'ex.032',sourcePage:34,sourcePages:[34,131],sourceWork:'Cosmic Rays [take 5]',analysisRef:'Cを軸とするd-c-b-c turn; ex.162でも同じoperatorをC Major line生成に使用',adaptation:'Short C-major pedagogical turn; surrounding Parker phrase is not copied'};
const STAGE9_SOURCE={type:'hamase',hamaseRef:'ex.071',hamaseRefs:['ex.071','ex.085'],sourcePage:50,sourcePages:[50,58],sourceWork:'Lady be Good',analysisRef:'複数コードの1→7接続が一つの長い下降LINEAR LINEを作る原理',adaptation:'C-major pedagogical reduction using the already-known C–B–A–G–F–E–D–C line; not a transcription or transposition of Lester Young’s phrase'};
const STAGE10_RELATIVE_SOURCE={type:'hamase',hamaseRef:'ex.124',hamaseRefs:['ex.118','ex.122','ex.124'],sourcePage:93,sourcePages:[90,92,93],sourceWork:'My Old Flame [take 1]',analysisRef:'Dominantの高次3度堆積の内部からRelative Major / related chordsを切り出し、同じshapeを別機能として旋律化する',adaptation:'G7(13) pedagogical reduction in C: F major/FMaj7 is treated as the corresponding upper structure; no Parker phrase is copied'};
const STAGE10_FLAT5_SOURCE={type:'hamase',hamaseRef:'ex.129',sourcePage:98,sourceWork:'Cherokee',analysisRef:'Relative Majorの5度だけを半音下げる flatted fifths(1): 1–3–5–7 → 1–3–♭5–7',adaptation:'For G7, F–A–C–E becomes F–A–B–E (C lowered one semitone, enharmonically B natural in the C-key pedagogical notation)'};
const STAGE11_SHAPE_SOURCE={type:'hamase',hamaseRef:'ex.191',hamaseRefs:['ex.190','ex.191'],sourcePage:150,sourcePages:[149,150],analysisRef:'F6(b5)のAをAbへ下げてFm6(b5)へ接続するRelative Major→Relative Minorの一声変形',adaptation:'Ordinary F/Fm pedagogical staging of the verified F6/Fm6 process; no theory diagram is copied as playable notation'};
const STAGE11_LINE_SOURCE={type:'hamase',hamaseRef:'ex.191',hamaseRefs:['ex.190','ex.191'],sourcePage:150,sourcePages:[149,150],analysisRef:'Major-side changesの後にRelative Minor Fm6(b5)を接続してf–e–d–c–b–Abのlineを作る',adaptation:'Four-beat reduction of the verified Major→Minor line connection; G7 remains the visible baseline while only the final A→Ab changes'};
export const VARIANTS=[
  V('anchor-cg-01','anchor-do-sol','SEED',[N('C4',60,0,1),N('G4',67,1,1),N('C4',60,2,1),N('G4',67,3,1)],{allowedPresentation:TEACH}),
  V('anchor-gc-01','anchor-do-sol','CHANGE',[N('G4',67,0,1),N('C4',60,1,1),N('G4',67,2,1),N('C4',60,3,1)],{parentVariant:'anchor-cg-01',morphType:'CHANGE',morphTargets:[0,1,2,3],allowedPresentation:LEARN}),
  V('anchor-ccgg-01','anchor-do-sol','CHANGE',[N('C4',60,0,1),N('C4',60,1,1),N('G4',67,2,1),N('G4',67,3,1)],{parentVariant:'anchor-cg-01',morphType:'CHANGE',morphTargets:[1,3],allowedPresentation:LEARN}),
  V('do-sol-q-01','do-sol-in-time','SEED',[N('C4',60,0,1),N('C4',60,1,1),N('G4',67,2,1),N('C4',60,3,1)],{allowedPresentation:TEACH}),
  V('do-sol-rest-01','do-sol-in-time','CHANGE',[N('C4',60,0,1),R(1,1),N('G4',67,2,1),N('C4',60,3,1)],{parentVariant:'do-sol-q-01',morphType:'CHANGE',morphTargets:[1],allowedPresentation:LEARN}),
  V('do-sol-eighth-01','do-sol-in-time','EXTEND',[N('C4',60,0,.5),N('G4',67,.5,.5),N('C4',60,1,1),N('G4',67,2,1),N('C4',60,3,1)],{parentVariant:'do-sol-q-01',morphType:'EXTEND',morphTargets:[0,1],allowedPresentation:LEARN}),
  V('do-sol-pickup-01','do-sol-in-time','CHANGE',[R(0,.5),N('G4',67,.5,.5),N('C4',60,1,1),N('G4',67,2,1),N('C4',60,3,1)],{parentVariant:'do-sol-q-01',morphType:'CHANGE',morphTargets:[0,1],allowedPresentation:LEARN}),
  V('tonic-shape-01','tonic-shape','SEED',[N('C4',60,0,1),N('E4',64,1,1),N('G4',67,2,1),N('E4',64,3,1)],{allowedPresentation:TEACH}),
  V('tonic-shape-02','tonic-shape','CHANGE',[N('G4',67,0,1),N('E4',64,1,1),N('C4',60,2,1),N('E4',64,3,1)],{parentVariant:'tonic-shape-01',morphType:'CHANGE',morphTargets:[0,2],allowedPresentation:LEARN}),
  V('desc-mi-seed','descend-to-mi','SEED',[N('G4',67,0,2),N('E4',64,2,2)],{allowedPresentation:TEACH}),
  V('desc-mi-grow','descend-to-mi','GROW',[N('G4',67,0,1),N('F4',65,1,1),N('E4',64,2,2)],{parentVariant:'desc-mi-seed',morphType:'INSERT',morphTargets:[1],allowedPresentation:LEARN}),
  V('desc-do-seed','descend-to-do','SEED',[N('E4',64,0,2),N('C4',60,2,2)],{allowedPresentation:TEACH}),
  V('desc-do-grow','descend-to-do','GROW',[N('E4',64,0,1),N('D4',62,1,1),N('C4',60,2,2)],{parentVariant:'desc-do-seed',morphType:'INSERT',morphTargets:[1],allowedPresentation:LEARN}),
  V('desc-do-change','descend-to-do','CHANGE',[N('E4',64,0,.5),N('D4',62,.5,.5),N('C4',60,1,.5),N('B3',59,1.5,.5),N('C4',60,2,2)],{parentVariant:'desc-do-grow',morphType:'CHANGE',morphTargets:[3,4],allowedPresentation:LEARN}),
  V('second-c','second-harmonic-family','SEED',[N('C4',60,0,1),N('E4',64,1,1),N('G4',67,2,1),N('C5',72,3,1)],{allowedPresentation:TEACH,allowedHarmony:['C'],source:STAGE4_SOURCE}),
  V('second-c6','second-harmonic-family','GROW',[N('C4',60,0,1),N('E4',64,1,1),N('G4',67,2,1),N('A4',69,3,1)],{parentVariant:'second-c',morphType:'CHANGE',morphTargets:[3],allowedPresentation:LEARN,allowedHarmony:['C6'],source:STAGE4_SOURCE}),
  V('second-am7','second-harmonic-family','MOVE',[N('A3',57,0,1),N('C4',60,1,1),N('E4',64,2,1),N('G4',67,3,1)],{parentVariant:'second-c6',morphType:'CHANGE',morphTargets:[0,1,2,3],allowedPresentation:LEARN,allowedHarmony:['Am7'],source:STAGE4_SOURCE}),
  V('second-dm7','second-harmonic-family','MOVE',[N('D4',62,0,1),N('F4',65,1,1),N('A4',69,2,1),N('C5',72,3,1)],{parentVariant:'second-am7',morphType:'CHANGE',morphTargets:[0,1,2,3],allowedPresentation:LEARN,allowedHarmony:['Dm7'],source:STAGE4_SOURCE}),
  V('ii-v-i-seed','ii-v-i-voice-line','SEED',[N('F4',65,0,2),N('F4',65,2,2),N('E4',64,4,4)],{allowedPresentation:TEACH,allowedHarmony:['Dm7','G7','Cmaj7'],source:STAGE5_SOURCE}),
  V('ii-v-i-grow','ii-v-i-voice-line','GROW',[N('F4',65,0,1),N('A4',69,1,1),N('F4',65,2,1),N('B4',71,3,1),N('E4',64,4,1),N('G4',67,5,1),N('E4',64,6,1),N('C4',60,7,1)],{parentVariant:'ii-v-i-seed',morphType:'CHANGE',morphTargets:[0,1,2,3,4,5,6,7],allowedPresentation:LEARN,allowedHarmony:['Dm7','G7','Cmaj7'],source:STAGE5_SOURCE}),
  V('harmony-descent-seed','harmony-born-descent','SEED',[N('C5',72,0,1),N('B4',71,1,1),N('A4',69,2,1),N('G4',67,3,1)],{allowedPresentation:TEACH,allowedHarmony:['Cmaj7','Am7'],source:STAGE6_HARMONY_SOURCE}),
  V('harmony-descent-grow','harmony-born-descent','GROW',[N('C5',72,0,1),N('B4',71,1,1),N('A4',69,2,1),N('G4',67,3,1),N('F4',65,4,1),N('E4',64,5,1),N('D4',62,6,1),N('C4',60,7,1)],{parentVariant:'harmony-descent-seed',morphType:'EXTEND',morphTargets:[4,5,6,7],allowedPresentation:LEARN,allowedHarmony:['Cmaj7','Am7','FMaj7','Dm7'],source:STAGE6_HARMONY_SOURCE}),
  V('line-descent-seed','line-born-descent','SEED',[N('G4',67,0,1),N('F4',65,1,1),N('E4',64,2,1),N('D4',62,3,1)],{allowedPresentation:TEACH,allowedHarmony:['G7','Em7'],source:STAGE6_LINE_SOURCE}),
  V('line-descent-grow','line-born-descent','GROW',[N('G4',67,0,1),N('F4',65,1,1),N('E4',64,2,1),N('D4',62,3,1),N('C4',60,4,2),N('B3',59,6,2)],{parentVariant:'line-descent-seed',morphType:'EXTEND',morphTargets:[4,5],allowedPresentation:LEARN,allowedHarmony:['G7','Em7','Cmaj7'],source:STAGE6_LINE_SOURCE}),
  V('gf-cell-seed','g-to-f-surfaces','SEED',[N('G4',67,0,2),N('F4',65,2,2)],{allowedPresentation:TEACH,allowedHarmony:['C'],source:STAGE7_SOURCE}),
  V('gf-cell-return','g-to-f-surfaces','GROW',[N('G4',67,0,1),N('A4',69,1,1),N('G4',67,2,1),N('F4',65,3,1)],{parentVariant:'gf-cell-seed',morphType:'INSERT',morphTargets:[1,2],allowedPresentation:LEARN,allowedHarmony:['C'],source:STAGE7_SOURCE}),
  V('gf-cell-fan','g-to-f-surfaces','DENSIFY',[N('G4',67,0,.5),N('B4',71,.5,.5),N('A4',69,1,1),N('G4',67,2,1),N('F4',65,3,1)],{parentVariant:'gf-cell-return',morphType:'CHANGE',morphTargets:[0,1,2],allowedPresentation:LEARN,allowedHarmony:['C'],source:STAGE7_SOURCE}),
  V('ge-orn-seed','ornament-to-mi','SEED',[N('G4',67,0,2),N('E4',64,2,2)],{allowedPresentation:TEACH,allowedHarmony:['C'],ornamentType:'NONE',targetRole:'E4'}),
  V('ge-orn-passing','ornament-to-mi','GROW',[N('G4',67,0,1),N('F4',65,1,1),N('E4',64,2,2)],{parentVariant:'ge-orn-seed',morphType:'INSERT',morphTargets:[1],allowedPresentation:LEARN,allowedHarmony:['C'],source:STAGE8_PASSING_SOURCE,ornamentType:'PASSING',targetRole:'E4'}),
  V('ge-orn-appoggiatura','ornament-to-mi','CHANGE',[N('G4',67,0,2),N('F4',65,2,1),N('E4',64,3,1)],{parentVariant:'ge-orn-passing',morphType:'CHANGE',morphTargets:[0,1,2],allowedPresentation:LEARN,allowedHarmony:['C'],source:STAGE8_APPOGGIATURA_SOURCE,ornamentType:'APPOGGIATURA',targetRole:'E4'}),
  V('ge-orn-neighbor','ornament-to-mi','GROW',[N('G4',67,0,.5),N('A4',69,.5,.5),N('G4',67,1,1),N('F4',65,2,1),N('E4',64,3,1)],{parentVariant:'ge-orn-appoggiatura',morphType:'EXTEND',morphTargets:[1,2],allowedPresentation:LEARN,allowedHarmony:['C'],source:STAGE8_NEIGHBOR_SOURCE,ornamentType:'NEIGHBOR',targetRole:'E4'}),
  V('ge-orn-chromatic','ornament-to-mi','CHANGE',[N('G4',67,0,.5),N('F#4',66,.5,.5),N('G4',67,1,1),N('F4',65,2,1),N('E4',64,3,1)],{parentVariant:'ge-orn-neighbor',morphType:'CHANGE',morphTargets:[1],allowedPresentation:LEARN,allowedHarmony:['C'],source:STAGE8_CHROMATIC_SOURCE,ornamentType:'CHROMATIC_APPROACH',targetRole:'G4→E4'}),
  V('turn-do-seed','turn-to-do','SEED',[N('D4',62,0,2),N('C4',60,2,2)],{allowedPresentation:TEACH,allowedHarmony:['C'],ornamentType:'NONE',targetRole:'C4'}),
  V('turn-do-grow','turn-to-do','GROW',[N('D4',62,0,1),N('C4',60,1,1),N('B3',59,2,1),N('C4',60,3,1)],{parentVariant:'turn-do-seed',morphType:'INSERT',morphTargets:[1,2],allowedPresentation:LEARN,allowedHarmony:['C'],source:STAGE8_TURN_SOURCE,ornamentType:'TURN',targetRole:'C4'}),
  V('long-line-2bar','long-line-through-changes','SEED',[N('C5',72,0,2),N('B4',71,2,2),N('A4',69,4,2),N('G4',67,6,2)],{allowedPresentation:TEACH,allowedHarmony:['Cmaj7','Am7'],source:STAGE9_SOURCE}),
  V('long-line-4bar','long-line-through-changes','GROW',[N('C5',72,0,2),N('B4',71,2,2),N('A4',69,4,2),N('G4',67,6,2),N('F4',65,8,2),N('E4',64,10,2),N('D4',62,12,2),N('C4',60,14,2)],{parentVariant:'long-line-2bar',morphType:'EXTEND',morphTargets:[4,5,6,7],allowedPresentation:LEARN,allowedHarmony:['Cmaj7','Am7','FMaj7','Dm7'],source:STAGE9_SOURCE}),
  V('rm-f-triad','relative-major-reinterpret','SEED',[N('F4',65,0,1),N('A4',69,1,1),N('C5',72,2,2)],{allowedPresentation:TEACH,allowedHarmony:['F','G7'],source:STAGE10_RELATIVE_SOURCE}),
  V('rm-fmaj7','relative-major-reinterpret','GROW',[N('F4',65,0,1),N('A4',69,1,1),N('C5',72,2,1),N('E5',76,3,1)],{parentVariant:'rm-f-triad',morphType:'EXTEND',morphTargets:[2,3],allowedPresentation:LEARN,allowedHarmony:['G7'],source:STAGE10_RELATIVE_SOURCE}),
  V('rm-fmaj7-flat5','relative-major-reinterpret','CHANGE',[N('F4',65,0,1),N('A4',69,1,1),N('B4',71,2,1),N('E5',76,3,1)],{parentVariant:'rm-fmaj7',morphType:'CHANGE',morphTargets:[2],allowedPresentation:LEARN,allowedHarmony:['G7'],source:STAGE10_FLAT5_SOURCE}),
  V('rmin-f6','relative-minor-shape','SEED',[N('F4',65,0,1),N('A4',69,1,1),N('C5',72,2,1),N('D5',74,3,1)],{allowedPresentation:TEACH,allowedHarmony:['F'],source:STAGE11_SHAPE_SOURCE}),
  V('rmin-f6-flat5','relative-minor-shape','CHANGE',[N('F4',65,0,1),N('A4',69,1,1),N('B4',71,2,1),N('D5',74,3,1)],{parentVariant:'rmin-f6',morphType:'CHANGE',morphTargets:[2],allowedPresentation:LEARN,allowedHarmony:['F'],source:STAGE11_SHAPE_SOURCE}),
  V('rmin-fm6-flat5','relative-minor-shape','CHANGE',[N('F4',65,0,1),N('Ab4',68,1,1),N('B4',71,2,1),N('D5',74,3,1)],{parentVariant:'rmin-f6-flat5',morphType:'CHANGE',morphTargets:[1],allowedPresentation:LEARN,allowedHarmony:['Fm'],source:STAGE11_SHAPE_SOURCE}),
  V('rmin-fm6','relative-minor-shape','CHANGE',[N('F4',65,0,1),N('Ab4',68,1,1),N('C5',72,2,1),N('D5',74,3,1)],{parentVariant:'rmin-fm6-flat5',morphType:'CHANGE',morphTargets:[2],allowedPresentation:LEARN,allowedHarmony:['Fm'],source:STAGE11_SHAPE_SOURCE}),
  V('rmin-line-major','relative-minor-line','SEED',[N('F4',65,0,.5),N('E4',64,.5,.5),N('D4',62,1,.5),N('C4',60,1.5,.5),N('B3',59,2,1),N('A3',57,3,1)],{allowedPresentation:TEACH,allowedHarmony:['G7'],source:STAGE11_LINE_SOURCE}),
  V('rmin-line-minor','relative-minor-line','CHANGE',[N('F4',65,0,.5),N('E4',64,.5,.5),N('D4',62,1,.5),N('C4',60,1.5,.5),N('B3',59,2,1),N('Ab3',56,3,1)],{parentVariant:'rmin-line-major',morphType:'CHANGE',morphTargets:[5],allowedPresentation:LEARN,allowedHarmony:['G7'],source:STAGE11_LINE_SOURCE}),
];
export const variantById=id=>VARIANTS.find(v=>v.variantId===id)||null;
export const variantsForFamily=familyId=>VARIANTS.filter(v=>v.familyId===familyId);
