import { EXERCISES, GROUPS, GROUP_LABELS, findExercise, solfege } from './src/exercises.js';
import { loadState, mutate, masteryOf, recordAttempt, setSettings, cMastery } from './src/storage.js';
import { renderNotation } from './src/notation.js';
import { demoPhrase, countIn, ensureAudio, audioStatus } from './src/audio.js';
import { initMic, capture, micStatus, stopMic } from './src/mic.js';
import { scoreAttempt } from './src/scoring.js';

const $ = (q, root=document) => root.querySelector(q);
const app = $('#app');
const GROUP_ICON={Pitch:'●',Scale:'↗',Arpeggio:'◇',Rhythm:'♪',Phrase:'⌁'};
let practiceRuntime = { busy:false, progress:0, countBeat:0, micError:null };

function currentBpm(){ const m=cMastery(); return m>=75?96:m>=45?84:m>=20?72:60; }
function navTo(path){ location.hash = path.startsWith('#')?path:`#${path}`; }
function pathParts(){ return (location.hash.replace(/^#/, '') || '/').split('/').filter(Boolean); }
function avgMastery(){ return cMastery(); }
function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}

function shell(content,{compact=false,active='home'}={}){
  app.innerHTML = `<div class="app-shell ${compact?'is-compact':''}"><header class="topbar"><button class="brand" data-nav="/" aria-label="ホーム"><span class="brand-mark">B</span><span><b>Bebop Reader</b><small>READ → SING → FLOW</small></span></button><div class="key-pill"><span>KEY</span><b>C</b></div></header><main>${content}</main>${compact?'':bottomNav(active)}</div>`;
  bindNav();
}
function bottomNav(active){ const items=[['home','/','今日','◉'],['library','/library','教材','▤'],['progress','/progress','進捗','◫'],['settings','/settings','設定','⚙']]; return `<nav class="bottom-nav">${items.map(([id,path,label,icon])=>`<button data-nav="${path}" class="${active===id?'active':''}"><span>${icon}</span><small>${label}</small></button>`).join('')}</nav>`; }
function bindNav(){ document.querySelectorAll('[data-nav]').forEach(el=>el.addEventListener('click',()=>navTo(el.dataset.nav))); }

function dailySession(){
  const s=loadState();
  const scored = EXERCISES.map((e,i)=>({e,i,m:s.mastery[e.id]||0,a:s.attempts[e.id]||0}));
  const weak=scored.filter(x=>x.a>0).sort((a,b)=>a.m-b.m || a.i-b.i).slice(0,3).map(x=>x.e);
  const fresh=scored.filter(x=>x.a===0).slice(0,4).map(x=>x.e);
  const review=scored.filter(x=>x.a>0&&x.m>=2).sort((a,b)=>a.i-b.i).slice(0,2).map(x=>x.e);
  const challenge=[...scored].reverse().find(x=>x.e.difficulty<=Math.max(2,Math.ceil(avgMastery()/20)+1))?.e;
  const out=[]; [...weak,...fresh,...review,challenge].filter(Boolean).forEach(e=>{if(!out.find(x=>x.id===e.id))out.push(e)});
  while(out.length<9){const e=EXERCISES[out.length];if(e&&!out.find(x=>x.id===e.id))out.push(e);else break;}
  return out.slice(0,9);
}
function startSession(){ const ids=dailySession().map(e=>e.id); mutate(s=>{s.session=ids;s.sessionIndex=0;}); navTo(`/practice/${ids[0]}`); }
function nextExerciseId(currentId){ const s=loadState(); if(s.session?.length){const i=s.session.indexOf(currentId);if(i>=0&&i<s.session.length-1){mutate(x=>x.sessionIndex=i+1);return s.session[i+1];}} const i=EXERCISES.findIndex(e=>e.id===currentId);return EXERCISES[(i+1)%EXERCISES.length].id; }

function renderHome(){
  const s=loadState(), mastery=avgMastery(), bpm=currentBpm(), session=dailySession();
  shell(`<section class="hero"><div class="eyebrow">TODAY · 7 MIN</div><h1>譜面を見て、<br><em>そのまま歌う。</em></h1><p>今日はC Major。音を一つずつ当てず、拍の中でフレーズとして読む。</p></section><section class="today-card card"><div class="today-top"><div><span class="label">今日のセッション</span><h2>${session.length} phrases</h2></div><div class="tempo-badge"><span>♩</span><b>${bpm}</b></div></div><div class="mini-path">${session.slice(0,7).map((e,i)=>`<span class="${i===0?'now':''}" title="${escapeHtml(e.title)}">${GROUP_ICON[e.group]}</span>`).join('<i></i>')}</div><button class="primary big" id="start-session">はじめる <span>→</span></button></section><section class="metrics-grid"><div class="metric card"><span>STREAK</span><b>${s.streak||0}<small>日</small></b><em>連続</em></div><div class="metric card"><span>C MAJOR</span><b>${mastery}<small>%</small></b><em>mastery</em></div></section><section class="section-head"><div><span class="eyebrow">TEMPO TRACK</span><h3>オンタイムの速度</h3></div><b>♩=${bpm}</b></section><div class="tempo-track card">${[60,72,84,96].map(t=>`<div class="tempo-step ${t<=bpm?'done':''} ${t===bpm?'current':''}"><span>${t<=bpm?'✓':'·'}</span><b>${t}</b></div>`).join('<i></i>')}</div><section class="locked-worlds"><div class="world active"><b>C</b><span>Major</span><small>NOW</small></div><div class="world"><b>F</b><span>Major</span><small>LOCKED</small></div><div class="world"><b>B♭</b><span>Major</span><small>LOCKED</small></div><div class="world wide"><b>12</b><span>Blues</span><small>PHASE 2</small></div></section>`,{active:'home'});
  $('#start-session').addEventListener('click',startSession);
}
function practiceHeader(ex){ const s=loadState(), idx=s.session?.indexOf(ex.id), total=s.session?.length||0; return `<div class="practice-meta"><button class="icon-btn" data-nav="/">×</button><div class="lesson-progress"><div style="width:${idx>=0&&total?((idx+1)/total*100):30}%"></div></div><span>${idx>=0&&total?`${idx+1}/${total}`:'PRACTICE'}</span></div>`; }
function renderPractice(ex){
  const settings=loadState().settings;
  shell(`${practiceHeader(ex)}<section class="practice-title"><div><span class="eyebrow">${escapeHtml(GROUP_LABELS[ex.group])}</span><h1>${escapeHtml(ex.title)}</h1></div><div class="practice-spec"><span>C</span><span>♩ ${ex.bpm}</span></div></section>${ex.chords?.length?`<div class="chord-strip">${ex.chords.map(c=>`<span>${escapeHtml(c)}</span>`).join('<i>→</i>')}</div>`:''}<section class="score-card"><div class="score-wrap"><div id="score"></div><div id="playhead" class="playhead"></div></div><div id="solfege" class="solfege-row ${settings.solfege?'':'hidden'}">${ex.notes.map(n=>`<span style="flex:${n.duration}">${n.rest?'':solfege(n.pitch)}</span>`).join('')}</div></section><div id="attempt-state" class="attempt-state"><span class="pulse-dot"></span><b>譜面から先に音を聴く</b><small>準備できたら「歌う」</small></div><div id="count-display" class="count-display hidden">1</div><div class="practice-actions"><button class="secondary" id="listen-btn"><span>▶</span> お手本</button><button class="primary sing" id="sing-btn"><span class="mic-icon">●</span> 歌う</button></div><div id="mic-fallback" class="fallback hidden"><b>マイクが使えません</b><p>採点なしで、伴奏と譜面だけの練習を続けられます。</p><button class="secondary" id="self-practice">採点なしで練習</button></div><p class="attempt-note">歌唱中は正誤を表示しません。結果はフレーズ終了後にまとめて返します。</p>`,{compact:true});
  renderNotation($('#score'),ex);
  $('#listen-btn').addEventListener('click',async(e)=>{e.currentTarget.disabled=true;try{await demoPhrase(ex);}catch(err){toast(String(err.message||err));}setTimeout(()=>e.currentTarget.disabled=false,ex.totalBeats*60/ex.bpm*1000+200);});
  $('#sing-btn').addEventListener('click',()=>runAttempt(ex));
}
async function runAttempt(ex){
  if(practiceRuntime.busy)return; practiceRuntime.busy=true; const sing=$('#sing-btn'), listen=$('#listen-btn'), state=$('#attempt-state'), count=$('#count-display'); sing.disabled=true;listen.disabled=true;
  try{await ensureAudio();try{await initMic();practiceRuntime.micError=null;}catch(err){practiceRuntime.micError=err;throw err;}state.innerHTML='<span class="pulse-dot gold"></span><b>COUNT IN</b><small>4拍後に入る</small>';count.classList.remove('hidden');await countIn(ex.bpm,b=>{count.textContent=b;count.animate([{transform:'scale(.7)',opacity:.3},{transform:'scale(1)',opacity:1}],{duration:180});});count.classList.add('hidden');state.innerHTML='<span class="pulse-dot live"></span><b>SING</b><small>画面ではなく譜面を見る</small>';document.body.classList.add('attempting');const ph=$('#playhead'), duration=ex.totalBeats*60/ex.bpm;ph.classList.add('active');ph.style.left='11%';const samples=await capture(duration,ex,p=>{ph.style.left=`${11+p*82}%`;});ph.classList.remove('active');document.body.classList.remove('attempting');const result=scoreAttempt(ex,samples,loadState().settings.latencyMs||0);recordAttempt(ex,result);navTo(`/result/${ex.id}`);}catch(err){document.body.classList.remove('attempting');count.classList.add('hidden');const fb=$('#mic-fallback');fb.classList.remove('hidden');state.innerHTML='<span class="pulse-dot error"></span><b>マイク入力を確認</b><small>設定またはブラウザ権限を確認</small>';$('#self-practice')?.addEventListener('click',()=>runSelfPractice(ex),{once:true});sing.disabled=false;listen.disabled=false;}finally{practiceRuntime.busy=false;}
}
async function runSelfPractice(ex){try{await ensureAudio();$('#mic-fallback').classList.add('hidden');const state=$('#attempt-state');state.innerHTML='<span class="pulse-dot gold"></span><b>COUNT IN</b><small>採点なしモード</small>';await countIn(ex.bpm);document.body.classList.add('attempting');const ph=$('#playhead'),duration=ex.totalBeats*60/ex.bpm;ph.classList.add('active');const start=performance.now();await new Promise(resolve=>{const f=()=>{const p=(performance.now()-start)/1000/duration;ph.style.left=`${11+Math.min(1,p)*82}%`;if(p>=1)resolve();else requestAnimationFrame(f)};f()});ph.classList.remove('active');document.body.classList.remove('attempting');const result={mode:'self',pitch:null,time:null,flow:null,overall:null,notes:[],coaching:'採点なしで完走しました。止まらず拍の中を進めたか、自分の耳で確認しよう。'};recordAttempt(ex,result);navTo(`/result/${ex.id}`);}catch(err){toast(err.message||String(err));}}
function scoreRing(value,label){const v=value??0;const color=v>=90?'#63b391':v>=75?'#c9a55c':'#d66d60';return `<div class="score-ring" style="--v:${v};--ring:${color}"><div><b>${value==null?'—':value}</b><span>${label}</span></div></div>`;}
function renderResult(ex){
  const s=loadState(), r=s.lastResult?.exerciseId===ex.id?s.lastResult:null;if(!r){navTo(`/practice/${ex.id}`);return;}const isPerfect=r.mode==='mic'&&r.overall>=94;
  shell(`<section class="result-hero ${isPerfect?'perfect':''}"><span class="eyebrow">${isPerfect?'PERFECT PHRASE':'RESULT'}</span><h1>${isPerfect?'流れた。':'もう一度、耳に戻す。'}</h1><p>${escapeHtml(r.coaching)}</p></section><section class="result-scores card ${r.mode==='self'?'self-mode':''}">${r.mode==='mic'?`${scoreRing(r.pitch,'PITCH')}${scoreRing(r.time,'TIME')}${scoreRing(r.flow,'FLOW')}`:`<div class="self-complete"><span>✓</span><b>完走</b><small>SELF PRACTICE</small></div>`}</section><section class="result-score-card score-card"><div id="result-score"></div></section>${r.mode==='mic'?`<section class="note-analysis card"><div class="section-head compact"><div><span class="eyebrow">NOTE MAP</span><h3>どこで外れたか</h3></div><b>${r.notes.filter(n=>n.ok).length}/${r.notes.length}</b></div><div class="note-chips">${r.notes.map(n=>`<div class="note-chip ${n.ok?'ok':'miss'}"><b>${escapeHtml(n.target)}</b><span>${n.medianCents==null?'—':`${Math.round(n.medianCents)}¢`}</span><small>${n.onsetErrorMs>=900?'no voice':`${Math.round(n.onsetErrorMs)}ms`}</small></div>`).join('')}</div></section>`:''}<div class="result-actions"><button class="secondary big" id="retry">もう一度</button><button class="primary big" id="next">次へ <span>→</span></button></div><button class="text-btn" data-nav="/">今日はここまで</button>`,{compact:true});
  renderNotation($('#result-score'),ex,{resultNotes:r.notes||[]});$('#retry').addEventListener('click',()=>navTo(`/practice/${ex.id}`));$('#next').addEventListener('click',()=>navTo(`/practice/${nextExerciseId(ex.id)}`));if(isPerfect)confettiLite();
}
function renderLibrary(){shell(`<section class="page-title"><span class="eyebrow">LIBRARY · C MAJOR</span><h1>語彙を増やす</h1><p>同じ音楽データを、読譜・発声・理論の別角度から反復する。</p></section><div class="library-groups">${GROUPS.map(g=>{const items=EXERCISES.filter(e=>e.group===g);const avg=Math.round(items.reduce((a,e)=>a+(masteryOf(e.id)||0),0)/items.length*20);return `<section class="library-group"><div class="group-head"><div class="group-icon">${GROUP_ICON[g]}</div><div><h2>${GROUP_LABELS[g]}</h2><span>${items.length} exercises</span></div><b>${avg}%</b></div><div class="exercise-list">${items.map(e=>`<button class="exercise-row" data-nav="/practice/${e.id}"><div><span>${escapeHtml(e.title)}</span><small>♩${e.bpm} · Lv.${e.difficulty}${e.chords?.length?' · '+escapeHtml(e.chords.join(' → ')):''}</small></div><div class="mastery-dots">${[1,2,3,4,5].map(i=>`<i class="${i<=Math.floor(masteryOf(e.id)||0)?'on':''}"></i>`).join('')}</div></button>`).join('')}</div></section>`;}).join('')}</div>`,{active:'library'});}
function renderProgress(){const m=avgMastery(),bpm=currentBpm();shell(`<section class="page-title"><span class="eyebrow">MAP</span><h1>ジャズ言語への道</h1><p>キーを増やす前に、Cをオンタイムで身体に入れる。</p></section><section class="mastery-hero card"><div class="big-number">${m}<small>%</small></div><div><span>C MAJOR</span><h2>${m<20?'Landmarks':m<45?'Scale & Chords':m<75?'Jazz Phrases':'Ready to transpose'}</h2><p>現在のテンポ ♩=${bpm}</p></div></section><div class="skill-map"><div class="map-node done"><span>01</span><div><b>C Major</b><small>読譜 → 視唱</small></div><em>ACTIVE</em></div><i></i><div class="map-node locked"><span>02</span><div><b>F Major</b><small>同じ語彙を移調</small></div><em>LOCKED</em></div><i></i><div class="map-node locked"><span>03</span><div><b>B♭ Major</b><small>♭系の視認</small></div><em>LOCKED</em></div><i></i><div class="map-node future"><span>04</span><div><b>12-Bar Blues</b><small>読む → つなぐ → 1 chorus</small></div><em>PHASE 2</em></div><i></i><div class="map-node future"><span>05</span><div><b>Rhythm Changes</b><small>bebop vocabulary</small></div><em>GOAL</em></div></div><section class="section-head"><div><span class="eyebrow">MASTERY BY SKILL</span><h3>Cの内訳</h3></div></section><div class="bars card">${GROUPS.map(g=>{const a=EXERCISES.filter(e=>e.group===g);const p=Math.round(a.reduce((x,e)=>x+(masteryOf(e.id)||0),0)/(a.length*5)*100);return `<div><span>${GROUP_LABELS[g]}</span><i><b style="width:${p}%"></b></i><em>${p}%</em></div>`}).join('')}</div>`,{active:'progress'});}
function renderSettings(){
  const s=loadState(),st=s.settings, diag=micStatus();
  shell(`<section class="page-title"><span class="eyebrow">SETTINGS</span><h1>耳と端末を合わせる</h1><p>iPhoneでは音声開始にユーザー操作が必要です。最初のタップで音声エンジンを起動します。</p></section><section class="settings-card card"><div class="setting-row"><div><b>ドレミ表示</b><small>初期は表示。慣れたら消す。</small></div><label class="switch"><input id="solfege-switch" type="checkbox" ${st.solfege?'checked':''}><span></span></label></div><div class="setting-row column"><div><b>入力レイテンシ補正</b><small>判定が歌声より遅れて見える場合に調整</small></div><div class="range-line"><input id="latency" type="range" min="-200" max="400" step="10" value="${st.latencyMs||0}"><output id="latency-out">${st.latencyMs||0} ms</output></div></div></section><section class="settings-card card"><div class="setting-row"><div><b>マイクをテスト</b><small id="mic-label">${diag.status==='ready'?'利用可能':'未テスト'}</small></div><button class="secondary small" id="mic-test">テスト</button></div><div id="mic-live" class="mic-live hidden"><span>Detected</span><b>—</b><small>Hz —</small></div></section><section class="settings-card card"><div class="setting-row"><div><b>ホーム画面に追加</b><small>Safariの共有 →「ホーム画面に追加」</small></div><button class="secondary small" id="install-help">手順</button></div></section><details class="diagnostics card"><summary>Developer diagnostics</summary><div id="diag-body"><p><span>AudioContext</span><b>${audioStatus()}</b></p><p><span>Mic</span><b>${diag.status}</b></p><p><span>Detected</span><b>${diag.note||'—'} / ${diag.hz?diag.hz.toFixed(1):'—'} Hz</b></p><p><span>Latency</span><b>${st.latencyMs||0} ms</b></p><p><span>VexFlow</span><b>${window.VexFlow?'ready':'missing'}</b></p><p><span>Tone</span><b>${window.Tone?'ready':'missing'}</b></p></div></details><button class="danger-text" id="reset-data">学習データをリセット</button>`,{active:'settings'});
  $('#solfege-switch').addEventListener('change',e=>setSettings({solfege:e.target.checked}));$('#latency').addEventListener('input',e=>{$('#latency-out').value=`${e.target.value} ms`;setSettings({latencyMs:Number(e.target.value)});});$('#mic-test').addEventListener('click',async()=>{try{await initMic();$('#mic-label').textContent='利用可能';const box=$('#mic-live');box.classList.remove('hidden');const start=performance.now();const loop=()=>{const d=micStatus();box.querySelector('b').textContent=d.note||'—';box.querySelector('small').textContent=`Hz ${d.hz?d.hz.toFixed(1):'—'} · clarity ${d.clarity?.toFixed(2)||'0.00'}`;if(performance.now()-start<6000)requestAnimationFrame(loop)};loop();}catch(err){$('#mic-label').textContent='利用できません';toast(err.message||String(err));}});$('#install-help').addEventListener('click',()=>toast('iPhone: Safari下部の共有ボタン →「ホーム画面に追加」→「追加」'));$('#reset-data').addEventListener('click',()=>{if(confirm('mastery・streak・設定をすべて消しますか？')){localStorage.removeItem('bebop-reader-state-v1');location.reload();}});
}
function toast(msg){const t=document.createElement('div');t.className='toast';t.textContent=msg;document.body.appendChild(t);requestAnimationFrame(()=>t.classList.add('show'));setTimeout(()=>{t.classList.remove('show');setTimeout(()=>t.remove(),250)},3300);}
function confettiLite(){for(let i=0;i<18;i++){const p=document.createElement('i');p.className='confetti';p.style.left=`${15+Math.random()*70}%`;p.style.setProperty('--x',`${(Math.random()-.5)*160}px`);p.style.animationDelay=`${Math.random()*.25}s`;p.style.background=Math.random()>.5?'#c9a55c':'#f1e8d4';document.body.appendChild(p);setTimeout(()=>p.remove(),1600);}}
function route(){document.body.classList.remove('attempting');practiceRuntime.busy=false;const parts=pathParts();if(!parts.length)return renderHome();if(parts[0]==='practice')return renderPractice(findExercise(parts[1]));if(parts[0]==='result')return renderResult(findExercise(parts[1]));if(parts[0]==='library')return renderLibrary();if(parts[0]==='progress')return renderProgress();if(parts[0]==='settings')return renderSettings();renderHome();}
window.addEventListener('hashchange',route);window.addEventListener('beforeunload',()=>stopMic());if('serviceWorker' in navigator && location.protocol.startsWith('http')) navigator.serviceWorker.register('./sw.js').catch(()=>{});route();
